name: Autograding Navigation Assignment

on:
  push:
  pull_request:
  workflow_dispatch:

permissions:
  checks: write
  actions: read
  contents: read

jobs:
  run-navigation-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'  # Prevents bot-triggered runs
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Make test script executable
        run: chmod +x test_navigation.sh

      - name: Run Navigation Test Script
        run: bash test_navigation.sh

      - name: Autograding Reporter
        uses: education/autograding-grading-reporter@v1
        with:
          reporter: "terminal-navigation-test"