name: Autograding Terminal Navigation Tests

on:
  push:
  pull_request:
  workflow_dispatch:
  repository_dispatch:

permissions:
  checks: write
  actions: read
  contents: read

jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'  # Prevents bot-triggered runs
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Make test script executable
        run: chmod +x test_navigation.sh

      - name: Run Navigation Test Script
        run: bash test_navigation.sh  # Executes the student’s test script

      - name: Autograding Reporter
        uses: classroom-resources/autograding-grading-reporter@v1
        with:
          runners: terminal-navigation-test